export {default as Navbar} from './navbar'
export {default as HeroSection} from './hero'
export {default as FeaturedProducts} from './featuredProducts'
export {default as ProductList} from './productList'
export {default as FAQSection} from './faqs'
export {default as MobileNavBar} from './mobileNavBar'
export {default as Footer} from './footer'